#!/bin/bash
source ~/.bash_profile 2>/dev/null || source ~/.profile 2>/dev/null
export PATH="$HOME/.local/bin:/opt/homebrew/bin:$PATH"

echo "[$(date)] Starting blog draft generation..." >> ~/waymarked-pinterest/cron.log

cd ~/repos/waymarked
git checkout main
git pull origin main

CLAUDECODE= claude --dangerously-skip-permissions -p "You are the Waymarked blog writer.

1. Read ~/waymarked-pinterest/learnings.md for brand voice and insights
2. Read the content/blog/ directory to see what posts already exist
3. Read ~/waymarked-pinterest/waymarked-pinterest.md for SEO keywords and brand knowledge
4. Pick a topic that does NOT already exist as a blog post. Prioritize these topics in order:
   - Gift guides (travel gifts, honeymoon gifts, anniversary gifts)
   - Travel wall art / home decor
   - Travel memory preservation
   - Specific occasion content
5. Write a complete blog post as an .mdx file with proper frontmatter:
   ---
   title: \"Post Title Here\"
   description: \"SEO meta description, 150-160 chars\"
   date: \"$(date +%Y-%m-%d)\"
   slug: \"url-slug-here\"
   category: \"gift-guides\"
   tags: [\"tag1\", \"tag2\"]
   image: \"/blog/images/hero.jpg\"
   imageAlt: \"Alt text\"
   readingTime: 8
   ---
6. The post should be 800-1200 words
7. Include at least one mention of Waymarked with a link to /create
8. Include internal links to other blog posts if they exist
9. Use natural SEO keywords (custom travel map, personalized travel gift, travel wall art, etc.)
10. Save to content/blog/SLUG.mdx
11. IMPORTANT: As your very last output, print ONLY a one-line plain text summary (no markdown, no bold, no asterisks) in this exact format:
    SUMMARY: [post-title] | [slug] | [category]

Do NOT commit or push. This is a draft for human review." --model sonnet --output-format text >> ~/waymarked-pinterest/cron.log 2>&1

# Extract summary parts
SUMMARY_LINE=$(grep 'SUMMARY:' ~/waymarked-pinterest/cron.log | tail -1 | sed 's/.*SUMMARY:[* ]*//')
TITLE=$(echo "$SUMMARY_LINE" | cut -d'|' -f1 | xargs)
SLUG=$(echo "$SUMMARY_LINE" | cut -d'|' -f2 | xargs)
CATEGORY=$(echo "$SUMMARY_LINE" | cut -d'|' -f3 | xargs)

if [ -n "$SLUG" ] && [ -f "content/blog/${SLUG}.mdx" ]; then
  BRANCH="draft/blog-${SLUG}"
  git checkout -b "$BRANCH"
  git add "content/blog/${SLUG}.mdx"
  git commit -m "Draft blog post: ${TITLE}"
  git push -u origin "$BRANCH"

  PR_URL=$(gh pr create \
    --title "Blog draft: ${TITLE}" \
    --body "$(cat <<EOF
## New blog post for review

**Title:** ${TITLE}
**Category:** ${CATEGORY}
**Slug:** \`${SLUG}\`

Review the post below. Merge to publish, close to reject.

---
*Auto-generated by Waymarked blog automation*
EOF
)" 2>&1)

  git checkout main

  curl -s \
    -H "Title: Blog draft ready" \
    -H "Tags: memo" \
    -H "Click: ${PR_URL}" \
    -d "${TITLE} — tap to review PR" \
    ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1

  echo "[$(date)] PR created: ${PR_URL}" >> ~/waymarked-pinterest/cron.log
else
  git checkout main
  if [ -n "$SUMMARY_LINE" ]; then
    curl -s \
      -H "Title: Blog draft ready" \
      -H "Tags: memo" \
      -d "$SUMMARY_LINE" \
      ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1
  else
    curl -s \
      -H "Title: Blog draft" \
      -H "Tags: warning" \
      -d "Blog generation ran but couldn't extract summary. Check cron.log" \
      ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1
  fi
fi

echo "[$(date)] Blog draft generation complete." >> ~/waymarked-pinterest/cron.log
