#!/bin/bash
source ~/.bash_profile 2>/dev/null || source ~/.profile 2>/dev/null
export PATH="$HOME/.local/bin:/opt/homebrew/bin:$PATH"

echo "[$(date)] Starting pin generation..." >> ~/waymarked-pinterest/cron.log

cd ~/repos/waymarked
git checkout main
git reset --hard origin/main
git pull origin main

# Snapshot existing exports before generation
BEFORE_FILES=$(ls ~/waymarked-pinterest/exports/*.png 2>/dev/null | sort)

CLAUDECODE= /opt/homebrew/bin/gtimeout 600 claude --dangerously-skip-permissions -p "You are the Waymarked Pinterest automation.

1. Read ~/waymarked-pinterest/learnings.md for rules and preferences
2. Read ~/waymarked-pinterest/audit.json for generation history
3. Read ~/waymarked-pinterest/waymarked-pinterest.md for your full skill instructions
4. Scan ~/repos/waymarked/content/blog/*.mdx — read each file's frontmatter (title, slug, tags, category) to know what blog posts exist for smart linking
5. Generate 3 new pin configurations (destination, style, board, title, description)
   - For each pin, pick the best blog post to link to based on angle/destination match (see Smart Link Strategy in skill file)
   - Record the chosen link in the pin_link field of audit.json
6. For each pin:
   a. Verify the dev server is running at http://localhost:3000 (curl check)
   b. Build the dev server URL with all parameters
   c. Run Playwright to capture the map PNG via the script in the skill file
   d. Save to ~/waymarked-pinterest/exports/
   e. Add entry to audit.json with status pending_review
6. Write a summary to ~/waymarked-pinterest/pending-review.md listing each pin with destination, style, board, description
7. IMPORTANT: As your very last output, print ONLY a one-line plain text summary (no markdown, no bold, no asterisks) in this exact format:
   SUMMARY: [destination1] ([style1]), [destination2] ([style2]), [destination3] ([style3])

Do NOT post to Pinterest. These are for human review only." --model sonnet --output-format text >> ~/waymarked-pinterest/cron.log 2>&1

# Find newly created PNG files
AFTER_FILES=$(ls ~/waymarked-pinterest/exports/*.png 2>/dev/null | sort)
NEW_FILES=$(comm -13 <(echo "$BEFORE_FILES") <(echo "$AFTER_FILES"))

# Extract summary
SUMMARY_LINE=$(grep 'SUMMARY:' ~/waymarked-pinterest/cron.log | tail -1 | sed 's/.*SUMMARY:[* ]*//')

if [ -n "$NEW_FILES" ] && [ -n "$SUMMARY_LINE" ]; then
  # Load R2 env vars
  export $(grep "^R2_" .env.local | xargs)

  # Compress and upload each new pin to R2, build image markdown
  IMAGE_MD=""
  for f in $NEW_FILES; do
    FNAME=$(basename "$f" .png)
    JPEG_PATH="/tmp/${FNAME}_review.jpg"
    # Convert to JPEG and resize to max 1200px wide for GitHub preview
    sips -s format jpeg -s formatOptions 70 -Z 1200 "$f" --out "$JPEG_PATH" > /dev/null 2>&1
    URL=$(node ~/repos/waymarked/upload-to-r2.mjs "$JPEG_PATH" "reviews/pins/${FNAME}.jpg")
    rm -f "$JPEG_PATH"
    IMAGE_MD="${IMAGE_MD}### ${FNAME}\n![${FNAME}](${URL})\n\n"
  done

  # Read pending-review.md for pin details
  DETAILS=""
  if [ -f ~/waymarked-pinterest/pending-review.md ]; then
    DETAILS=$(cat ~/waymarked-pinterest/pending-review.md)
  fi

  # Create GitHub Issue
  ISSUE_URL=$(gh issue create \
    --title "Pin review: ${SUMMARY_LINE}" \
    --body "$(cat <<EOF
## Pins for Review

${SUMMARY_LINE}

### Pin Details

${DETAILS}

### Pin Images

$(echo -e "$IMAGE_MD")

---
**To approve:** Comment which pins to post (e.g. "approve all" or "approve gen_021, reject gen_022")
**To reject:** Close this issue with a comment explaining why

*Auto-generated by Waymarked pin automation*
EOF
)" 2>&1)

  curl -s \
    -H "Title: 3 new pins ready" \
    -H "Tags: pushpin" \
    -H "Click: ${ISSUE_URL}" \
    -d "${SUMMARY_LINE} — tap to review" \
    ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1

  echo "[$(date)] Issue created: ${ISSUE_URL}" >> ~/waymarked-pinterest/cron.log
else
  if [ -n "$SUMMARY_LINE" ]; then
    curl -s \
      -H "Title: 3 new pins ready" \
      -H "Tags: pushpin" \
      -d "$SUMMARY_LINE" \
      ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1
  else
    curl -s \
      -H "Title: Pinterest pins" \
      -H "Tags: warning" \
      -d "Pin generation ran but couldn't extract summary. Check cron.log" \
      ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1
  fi
fi

echo "[$(date)] Pin generation complete." >> ~/waymarked-pinterest/cron.log
