#!/bin/bash
source ~/.bash_profile 2>/dev/null || source ~/.profile 2>/dev/null
export PATH="$HOME/.local/bin:/opt/homebrew/bin:$PATH"

echo "[$(date)] Starting blog draft generation..." >> ~/waymarked-pinterest/cron.log

cd ~/repos/waymarked
git checkout main
git reset --hard origin/main
git pull origin main

CLAUDECODE= claude --dangerously-skip-permissions -p "You are the Waymarked blog writer.

1. Read ~/waymarked-pinterest/learnings.md for brand voice and insights
2. Read the content/blog/ directory — read the frontmatter of every existing .mdx file (title, slug, category, tags)
3. Read ~/waymarked-pinterest/waymarked-pinterest.md for SEO keywords and brand knowledge

4. TOPIC SELECTION — follow this process exactly:

   The blog is organized into three topical clusters. Google rewards depth within a cluster over breadth across topics.
   Completing a cluster (4-6 tightly related posts) before expanding is the strategy.

   CLUSTER A — Gift Guides (category: gift-guides)
   Goal: 6 posts. Target posts (write these before anything else in this cluster):
   - Pillar: \"Best Custom Map Gifts for Every Occasion\" (slug: best-custom-map-gifts)
   - \"Custom Map Gifts for Weddings\" (slug: custom-map-gifts-weddings)
   - \"Graduation Gifts for Travelers\" (slug: graduation-gifts-travelers)
   - \"Birthday Gifts for Travel Lovers\" (slug: birthday-gifts-travel-lovers)
   - \"Housewarming Gifts for Travelers\" (slug: housewarming-gifts-travelers)
   - \"Christmas Gifts for Travelers\" (slug: christmas-gifts-travelers)
   Already written: best-anniversary-gifts, best-honeymoon-gifts, best-travel-gifts-2026 count toward this cluster.

   CLUSTER B — Map Wall Art (category: wall-art)
   Goal: 5 posts. Target posts:
   - Pillar: \"Custom Map Wall Art: The Complete Guide\" (slug: custom-map-wall-art-guide)
   - \"Gallery Wall Ideas with Travel Maps\" (slug: gallery-wall-ideas-travel-maps)
   - \"Vintage Map Prints for Home Decor\" (slug: vintage-map-prints-home-decor)
   - \"How to Frame a Custom Map Print\" (slug: how-to-frame-custom-map)
   - \"Minimalist Map Art for Modern Homes\" (slug: minimalist-map-art-modern-homes)

   CLUSTER C — Travel & Trip Documentation (category: travel-maps)
   Goal: 5 posts. Target posts:
   - Pillar: \"How to Create a Custom Travel Map\" (slug: how-to-create-custom-travel-map)
   - \"How to Document Your Travels\" (slug: how-to-document-travels)
   - \"Best Honeymoon Destinations to Map\" (slug: best-honeymoon-destinations-map)
   - \"How to Turn Trip Photos into Wall Art\" (slug: trip-photos-into-wall-art)
   - \"Road Trip Route Maps: A Custom Keepsake Idea\" (slug: road-trip-route-maps)

   PROCESS:
   a. For each cluster, count how many target posts already exist in content/blog/ (match by slug or close equivalent)
   b. Pick the cluster with the fewest existing posts
   c. Within that cluster, write the pillar post first if it doesn't exist. Otherwise write whichever target post is missing.
   d. If a cluster is complete (all target posts exist), move to the next least-complete cluster.
   e. NEVER write a post whose slug or topic is already covered by an existing post.

5. Write a complete blog post as an .mdx file with proper frontmatter:
   ---
   title: \"Post Title Here\"
   description: \"SEO meta description, 150-160 chars\"
   date: \"$(date +%Y-%m-%d)\"
   slug: \"url-slug-here\"
   category: \"gift-guides\"
   tags: [\"tag1\", \"tag2\"]
   image: \"/blog/images/hero.jpg\"
   imageAlt: \"Alt text\"
   readingTime: 8
   ---
6. The post should be 800-1200 words
7. Include at least one mention of Waymarked with a link to /create
8. Include internal links to other blog posts if they exist
9. Use natural SEO keywords (custom travel map, personalized travel gift, travel wall art, etc.)
10. Save to content/blog/SLUG.mdx
11. IMPORTANT: As your very last output, print ONLY a one-line plain text summary (no markdown, no bold, no asterisks) in this exact format:
    SUMMARY: [post-title] | [slug] | [category]

Do NOT commit or push. This is a draft for human review." --model sonnet --output-format text >> ~/waymarked-pinterest/cron.log 2>&1

# Extract summary parts
SUMMARY_LINE=$(grep 'SUMMARY:' ~/waymarked-pinterest/cron.log | tail -1 | sed 's/.*SUMMARY:[* ]*//')
TITLE=$(echo "$SUMMARY_LINE" | cut -d'|' -f1 | xargs)
SLUG=$(echo "$SUMMARY_LINE" | cut -d'|' -f2 | xargs)
CATEGORY=$(echo "$SUMMARY_LINE" | cut -d'|' -f3 | xargs)

if [ -n "$SLUG" ] && [ -f "content/blog/${SLUG}.mdx" ]; then
  BRANCH="draft/blog-${SLUG}"
  git checkout -b "$BRANCH"
  git add "content/blog/${SLUG}.mdx"
  git commit -m "Draft blog post: ${TITLE}"
  git push -u origin "$BRANCH"

  PR_URL=$(gh pr create \
    --title "Blog draft: ${TITLE}" \
    --body "$(cat <<EOF
## New blog post for review

**Title:** ${TITLE}
**Category:** ${CATEGORY}
**Slug:** \`${SLUG}\`

Review the post below. Merge to publish, close to reject.

---
*Auto-generated by Waymarked blog automation*
EOF
)" 2>&1)

  git checkout main

  curl -s \
    -H "Title: Blog draft ready" \
    -H "Tags: memo" \
    -H "Click: ${PR_URL}" \
    -d "${TITLE} — tap to review PR" \
    ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1

  echo "[$(date)] PR created: ${PR_URL}" >> ~/waymarked-pinterest/cron.log
else
  git checkout main
  if [ -n "$SUMMARY_LINE" ]; then
    curl -s \
      -H "Title: Blog draft ready" \
      -H "Tags: memo" \
      -d "$SUMMARY_LINE" \
      ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1
  else
    curl -s \
      -H "Title: Blog draft" \
      -H "Tags: warning" \
      -d "Blog generation ran but couldn't extract summary. Check cron.log" \
      ntfy.sh/$(grep NTFY_TOPIC ~/waymarked-pinterest/.env | cut -d= -f2) > /dev/null 2>&1
  fi
fi

echo "[$(date)] Blog draft generation complete." >> ~/waymarked-pinterest/cron.log
